### ISSUE TITLE
Add github link in header.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/demo-pttbbs#49]
1. github link to demo-pttbbs.
2. with github logo (need to check terms of use.)

**Comment by chhsiao1981** [comment]
https://github.com/logos

**Comment by chhsiao1981** [comment]
#50  added github logo～

However, the logo now becomes
navy-color octocat with orange background.

This setting may violate github policy.
(Create a modified version of the Octocat or GitHub logo)
(https://github.com/logos)

It's better that we stick to white octocat with rounded black background.

@solring

**Comment by solring** [comment]
Sorry, I don't really understand.
I thought the policy is about the shape and design, and color usually goes with the theme? And Font-awesome is actually violating github's policy? (also anyone who use it?)

Octocat is navy-color because it's hollow. It will be the same if you use the .png file they provide anyways?

Anyway I can still change it back to white .png if you think this is safer.

@chhsiao1981

**Comment by chhsiao1981** [comment]
Saw this post from github.

https://github.community/t/community-ama-featuring-mike-mcquaid-2021-02-26-2pm-utc/157900

Octocat is with the background-color,
and the surrounding-color is grey.

I think we are safe with navy-octocat and orange-surrounding for now.
